[package]
name = "augma-dps-meter"
version = "0.4.4"
description = "Augma DPS Meter"
authors = ["Augma"]
edition = "2021"

[lib]
name = "augma_dps_meter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libloading = "0.9"
lz4_flex = { version = "0.14", default-features = false, features = ["std", "safe-decode"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Diagnostics_Etw", "Win32_System_Time"] }

[profile.release]
lto = "thin"
opt-level = 3
strip = true